### ISSUE TITLE
Allow `package.json` to be dirty

### ISSUE THREAD

**Issue by jamestalmage** [jamestalmage/ava-codemods#14]
Right now the CLI requires a clean git working directory. The only issue with that is, if you've just done `npm i -D ava@latest`, your `package.json` is modified, meaning you need to either commit the bump in `package.json` first, or use the `--force` flag every time.

IMO a `--force` flag I'm deciding to use every time is kinda stupid. So I vote we make an exception for `package.json`.

**Comment by sindresorhus** [comment]
Let's do it.

**Comment by sotojuan** [comment]
Waiting on https://github.com/jamestalmage/is-git-clean/pull/1 to be reviewed so I can do this here!
