### ISSUE TITLE
Should not change code style

### ISSUE THREAD

**Issue by sindresorhus** [jamestalmage/ava-codemods#15]
When using ava-codemods on:

``` js
test(t => {
    t.same(fn.sync('1.tmp', {cwd: t.context.tmp}), [path.join(t.context.tmp, '1.tmp')]);
});
```

I get:

``` js
test(t => {
    t.deepEqual(
        fn.sync('1.tmp', {cwd: t.context.tmp}),
        [path.join(t.context.tmp, '1.tmp')]
    );
});
```

It should not change unrelated code.

And it doesn't even use the correct indentation. Source was tab indented, now it's 4 spaces.

**Comment by jamestalmage** [comment]
Fixed.

@jfmengels - Just FYI. `recast` attaches details about surrounding whitespace to each individual node, so the less of the AST you can replace the better. See: e375eb7

**Comment by jamestalmage** [comment]
fix deployed in `v0.2.1`

**Comment by jfmengels** [comment]
Ah, yes. Duly noted, thanks :+1:

**Comment by jfmengels** [comment]
cc @spudly you might want this tip too :)

**Comment by spudly** [comment]
Good info. Thanks!
