### ISSUE TITLE
Add ability to specify `from` and `to` AVA version as CLI flag

### ISSUE THREAD

**Issue by sindresorhus** [jamestalmage/ava-codemods#16]
I want to reuse the command in many projects and don't want to go through the interactive interface each time.

**Comment by jfmengels** [comment]
Do you want the ability to tell CLI to use the default files too? i.e. something like `ava-codemods --from 0.13.0 --to 0.14.0 --defaultFiles`

**Comment by jamestalmage** [comment]
I was thinking we could create an `upgrade ava` command that read the current version from package.json, bumped AVA and ran the appropriate codemods all at once.

**Comment by jfmengels** [comment]
Ah sounds nice!
