### ISSUE TITLE
ES6ify the code.

### ISSUE THREAD

**Issue by jamestalmage** [jamestalmage/ava-codemods#18]
The jscodeshift CLI automatically loads `babel/register` (it's still on `babel@5`).

No reason we shouldn't be able to do the same for our tests, etc.

**Comment by sindresorhus** [comment]
:+1:

**Comment by sotojuan** [comment]
What style do you guys prefer regarding arrow functions, `let` vs `const`, etc?

**Comment by jfmengels** [comment]
Pretty sure the style is decided in `xo`, just need to set the `esnext` mode in the config if I'm not mistaken.

**Comment by sotojuan** [comment]
Hm, stuff like using `const` or `let` in `require` statement doesn't seem to make a difference with `xo`.

**Comment by jamestalmage** [comment]
You have to set up the following in `package.json`:

``` json
"xo": {
  "esnext": true
}
```

**Comment by sotojuan** [comment]
For some reason it took a second run of `xo` to work, thanks! I'm taking care of this now.
