### ISSUE TITLE
Codemods for AVA cwd change

### ISSUE THREAD

**Issue by sindresorhus** [jamestalmage/ava-codemods#19]
We're gonna change the CWD in tests to the package root: https://github.com/sindresorhus/ava/issues/32

Should we have a codemod that ensures there's a `{cwd: __dirname}` in `childProcess` and not relative paths in `fs` methods?

**Comment by novemberborn** [comment]
`path` too.

**Comment by sindresorhus** [comment]
@novemberborn Example? 

By `not relative paths in fs methods?` I mean:
`fs.readFile('foo/bar')` => `fs.readFile(path.join(__dirname, 'foo/bar'))`

**Comment by novemberborn** [comment]
`path.resolve('foo/bar')`.

**Comment by a-s-o** [comment]
Hi, may I also request not using the nearest package.json as the CWD (i.e looking package.json upwards from the test file). This may cause issues in multi-package repos where the test runner is in the root but there are multiple packages with their own package.json in the project (example the [babel](https://github.com/babel/babel) repo).

I would like to suggest sticking with the directory where ava command is executed as that is the most obvious.

**Comment by novemberborn** [comment]
@a-s-o I've responded here: https://github.com/avajs/ava/issues/32#issuecomment-220842327
