### ISSUE TITLE
Current master branch won't work if released

### ISSUE THREAD

**Issue by DrewML** [jamestalmage/ava-codemods#26]
It looks like #24 didn't add account for how the cli would be consumed by users doing `npm install -g ava-codemods`.

That PR was commited to master a month after the last release, so the version in the npm registry is still ok. But, releasing a new version from `master` would not work in it's current state.

How would you like me to address this @sindresorhus? Options being:
1. Revert changes to use ES6
2. Compile in `prepublish` to a `dist` directory and ignore src files for publish
3. Run `babel-register` when users run the CLI

3 doesn't seem like the best idea for DX.

**Comment by jamestalmage** [comment]
`babel-register` - See https://github.com/avajs/ava-codemods/issues/18#issue-153552933

**Comment by sindresorhus** [comment]
`babel-register`

**Comment by sindresorhus** [comment]
I went with `#1`. Was just the imports that needed reverting. I couldn't get `babel/register` to work. Was easier this way. Probably much more performant too.
