### ISSUE TITLE
Conversion from Jest

### ISSUE THREAD

**Issue by sindresorhus** [jamestalmage/ava-codemods#32]
There exist a [conversion from AVA to Jest](https://github.com/skovhus/jest-codemods), so would be nice to have the reverse too.

@skovhus Interested? Asking since you have some experience with the Jest API now.
## 

Side question: I wonder if it would make more sense to have a separate project for each conversion? Not a big fan of bundling many binaries in one module.

**Comment by jfmengels** [comment]
I always thought we'd have one binary with a question asking whether you want to upgrade versions or migrate from another tool, and then another question asking from which.

**Comment by sindresorhus** [comment]
@jfmengels Could still have that even when separate tools though, by spawning CLI's in dependencies, but I'm good with having it here too. Was just a thought.
