### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by sindresorhus** [jamestalmage/ava-codemods#7]
We need to have docs in place in time for the next AVA release so users can easily codemod their tests.

**Comment by jamestalmage** [comment]
Yep. Do we want our own CLI by then? Or just use jscodemod CLI?

**Comment by sindresorhus** [comment]
Just codemod CLI, but we should document how to get and use it.

**Comment by sindresorhus** [comment]
Pretty much covered by https://github.com/jamestalmage/ava-codemods/commit/b8c8a42f5e03e55dc007d3eb352c8b28fed8840a, but I think we should explain what a codemod is.

**Comment by jfmengels** [comment]
> Yep. Do we want our own CLI by then?

I'd say yes :p

**Comment by sindresorhus** [comment]
Docs looks good now :)
